In [5]:
import torch

logits = torch.rand(1, 9)
print(f'Original Logits:\n{logits}')

Original Logits:
tensor([[0.4251, 0.6179, 0.3501, 0.3458, 0.2571, 0.2608, 0.3077, 0.4070, 0.0113]])


In [11]:
logits_m = torch.rand(3, 5)
print(f'Original Logits matrixs:\n{logits_m}')

Original Logits matrixs:
tensor([[0.1775, 0.3344, 0.0136, 0.0528, 0.6314],
        [0.1781, 0.2329, 0.6941, 0.8955, 0.6067],
        [0.7240, 0.4842, 0.2887, 0.6775, 0.9350]])


# Greedy

Here our objective it's to choose the bigger value in the indexs

Using the `torch.argmax()` will return the idx of the bigger value

In [24]:
next_token = torch.argmax(logits, keepdim=True) # will return a (1, 1)
sequence = torch.cat([logits, next_token], dim = 1) # the matrix are (1, 9) so excepts a (1, X) need to be (x, y) instead of (x)
print(f'So the next token choose its: {next_token}')
print(f'Matrix after the greedy and concat: {sequence}')

So the next token choose its: tensor([[1]])
Matrix after the greedy and concat: tensor([[0.4251, 0.6179, 0.3501, 0.3458, 0.2571, 0.2608, 0.3077, 0.4070, 0.0113,
         1.0000]])


In [29]:
next_token = torch.argmax(logits_m, dim=1, keepdim=True)
sequence = torch.cat([logits_m, next_token], dim = 1) # the matrix are (3, 5) so excepts a (3, X) need to be (x, y) instead of (x)
print(f'So the next token choose its: {next_token}')
print(f'Matrix after the greedy and concat: {sequence}')

So the next token choose its: tensor([[4],
        [3],
        [4]])
Matrix after the greedy and concat: tensor([[0.1775, 0.3344, 0.0136, 0.0528, 0.6314, 4.0000],
        [0.1781, 0.2329, 0.6941, 0.8955, 0.6067, 3.0000],
        [0.7240, 0.4842, 0.2887, 0.6775, 0.9350, 4.0000]])


# Temperature

Normally we use the `logits / temperatura` and after applied the softmax function `torch.softmax(logits, dim=1)`

In [35]:
temperature = 1.2
scaled_logits = logits / temperature
probs_normal = torch.softmax(logits, dim=1)
probs_logits = torch.softmax(scaled_logits, dim = 1)

print(f'Matrix of logits before the scaling: {logits}')
print(f'Matrix of logits afetr the scaling: {scaled_logits}')
print(f'=' * 50)
print(f'Matrix of softmax before the scaling: {probs_normal}')
print(f'Matrix of softmax after the scaling: {probs_logits}')


Matrix of logits before the scaling: tensor([[0.4251, 0.6179, 0.3501, 0.3458, 0.2571, 0.2608, 0.3077, 0.4070, 0.0113]])
Matrix of logits afetr the scaling: tensor([[0.3543, 0.5149, 0.2918, 0.2881, 0.2143, 0.2173, 0.2564, 0.3392, 0.0094]])
Matrix of softmax before the scaling: tensor([[0.1206, 0.1463, 0.1119, 0.1114, 0.1020, 0.1023, 0.1073, 0.1185, 0.0797]])
Matrix of softmax after the scaling: tensor([[0.1192, 0.1399, 0.1120, 0.1115, 0.1036, 0.1039, 0.1081, 0.1174, 0.0844]])


# Top K

In [39]:
values, idxs = torch.topk(logits, k=4) 
print(f'Original logits: {logits}')
print(f'Select the top 4 bigger values of the logits: {values} and their idx are: {idxs}')

Original logits: tensor([[0.4251, 0.6179, 0.3501, 0.3458, 0.2571, 0.2608, 0.3077, 0.4070, 0.0113]])
Select the top 4 bigger values of the logits: tensor([[0.6179, 0.4251, 0.4070, 0.3501]]) and their idx are: tensor([[1, 0, 7, 2]])


# Top P

# Sampling

In [49]:
next_token = torch.multinomial(logits, 1)
print(next_token)

tensor([[4]])
