# Weight Tying

Technique of 2 layers or something have the same weights

The `.weight` can acess the values of the weights

> We can acess and do a lot of things with that

In [3]:
import torch.nn as nn

layer1 = nn.Linear(4, 4)
layer2 = nn.Linear(4, 4)

print(f'=' * 50)
print(f'Before the tying')
print(f'L1: {layer1.weight}')
print(f'L2: {layer2.weight}')

layer2.weight = layer1.weight

print(f'=' * 50)
print(f'After the tying')
print(f'L1: {layer1.weight}')
print(f'L2: {layer2.weight}')



Before the tying
L1: Parameter containing:
tensor([[-0.4901, -0.2422, -0.0028, -0.2878],
        [ 0.0439,  0.3724,  0.4688, -0.4706],
        [ 0.0596,  0.2065, -0.3751,  0.1729],
        [ 0.2558, -0.0491, -0.3063, -0.0781]], requires_grad=True)
L2: Parameter containing:
tensor([[-0.3754,  0.3393,  0.0608, -0.4159],
        [ 0.0327, -0.2230, -0.1203,  0.1123],
        [ 0.2105, -0.2527, -0.0779, -0.4915],
        [ 0.2627, -0.0310, -0.3297,  0.4762]], requires_grad=True)
After the tying
L1: Parameter containing:
tensor([[-0.4901, -0.2422, -0.0028, -0.2878],
        [ 0.0439,  0.3724,  0.4688, -0.4706],
        [ 0.0596,  0.2065, -0.3751,  0.1729],
        [ 0.2558, -0.0491, -0.3063, -0.0781]], requires_grad=True)
L2: Parameter containing:
tensor([[-0.4901, -0.2422, -0.0028, -0.2878],
        [ 0.0439,  0.3724,  0.4688, -0.4706],
        [ 0.0596,  0.2065, -0.3751,  0.1729],
        [ 0.2558, -0.0491, -0.3063, -0.0781]], requires_grad=True)


# Others cool things

In [12]:
print(f'Shape of layer 1: {layer1.weight.shape}')
print(f'Acess the bias of layer1: {layer1.bias} and their shape: {layer1.bias.shape}')
print(f'Acess the bias of layer2: {layer2.bias}')

Shape of layer 1: torch.Size([4, 4])
Acess the bias of layer1: Parameter containing:
tensor([-0.2547, -0.1339,  0.0760,  0.2801], requires_grad=True) and their shape: torch.Size([4])
Acess the bias of layer2: Parameter containing:
tensor([ 0.0675,  0.0167, -0.4102,  0.4818], requires_grad=True)
