# Kernel Inicialization

When you inicialize some module for the neural network, already have a default kernel for the weight, but we can change them for some special cases and situations

## Families 

- ### 1. Uniform Inicalizations
    - The boundary is a concrete wall from $-a$ to $+a$. Wheres the a it's a limit number for the weights values
    - `nn.init.kernel_uniform_()`
- ### 2. Normal Inicializations
    - The inicialization doesn't have a hard limit. Instead, she uses the "Bell Curve" (Gaussian Distribution)
    - `nn.init.kernel_normal_()`

## Types

- ### 1. Xavier / Glorot
     - Uses the input and output neurons to calculate the $a$
     - `nn.init.xavier()`
- ### 2. He / Kaiming
     - Uses only the input neurons to calculate the $a$
     - `nn.init.kaiming()`

> We can think that Xavier's $a$ is lower, while Kaiming's is higher

> The default for the PyTorch it's the He / Kaiming


## PyTorch

1. `nn.init.kernelname_family_(layer, nonlinearity = 'activation_function' )`
    > Only the kaiming have the nonlinearity and passing the activation function the kernel will be a little update for the best configs
2. `.apply()`

In [2]:
# 1.

import torch
import torch.nn as nn

# Create the layer
layer1 = nn.Linear(3, 3)

# Before
print("--- Before ---")
print(layer1.weight)
print(layer1.bias)

# Apply the kernel inicialization
nn.init.xavier_normal_(layer1.weight)
nn.init.zeros_(layer1.bias)


# After
print("--- After ---")
print(layer1.weight)
print(layer1.bias)

--- Before ---
Parameter containing:
tensor([[ 0.4327, -0.0585, -0.1554],
        [-0.4780, -0.4951, -0.3086],
        [ 0.2969,  0.5074, -0.4824]], requires_grad=True)
Parameter containing:
tensor([-0.3262,  0.1135, -0.1752], requires_grad=True)
--- After ---
Parameter containing:
tensor([[-0.8112, -0.7361,  0.2958],
        [ 0.3744, -0.5472,  0.5004],
        [ 0.8568,  0.4023, -1.4305]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [ ]:
# 2. 

def weight_inicializations(module):

    if isinstance(module, nn.Linear):
        nn.init.kaiming_normal_(module.weight, nonlinearity='relu')
        
        if module.bias is not None:
            nn.init.zeros_(module.bias)
 
class Model(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fc1 = nn.Linear(3, 3)
        self.fc2 = nn.Linear(3, 3)
    
model = Model()
model.apply(weight_inicializations)




Model(
  (fc1): Linear(in_features=3, out_features=3, bias=True)
  (fc2): Linear(in_features=3, out_features=3, bias=True)
)