# Indexation

Techniques to acess data inside the arrays/matrixs/tensors. When you create an array will take up a space in the memory. So when you do a indexation operation we can create another array with the values or just have acess of this space in the memory.

# View vs Copy — NumPy / PyTorch
 
| Operation | View or Copy? |
|---|---|
| Basic slicing (indexing) `arr[1:3]`, `arr[::2]`, `mat[:, 1]` | **View** |
| Fancy indexing `arr[[1,3,5]]` | **Copy** |
| Boolean indexing `arr[arr > 10]` | **Copy** |



In [1]:
import torch

### 1. Basic Indexation (per position)

We gonna get an element or a part (slice) using the tensor name with [] and the position that we want `tensor[position]` for 1 element. For more we can slice using the logic `start:stop:step` inside the [], so `tensor[0:2:1]`.

> Always gonna be the view, so don't create other object in the memory

In [9]:
tensor = torch.arange(11)
print(f'Tensor created: {tensor} and we want to acess the second element (1), so: {tensor[1]}')
print(f'Tensor created: {tensor} and we want to acess the all the elements between the second and the seventh in a step of 1, so: {tensor[1:7:1]}')


""" 
More exemples below
"""

Tensor created: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) and we want to acess the second element (1), so: 1
Tensor created: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) and we want to acess the all the elements between the second and the seventh in a step of 1, so: tensor([1, 2, 3, 4, 5, 6])


' \nMore exemples below\n'

In [15]:
tensor[::2]

tensor([ 0,  2,  4,  6,  8, 10])

In [21]:
tensor[-3:]

tensor([ 8,  9, 10])

In [24]:
tensor[:-2:2]

tensor([0, 2, 4, 6, 8])

In [10]:
tensor[:]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2. Fancy Indexation

Gonna get the elements by a specific list. Always a array inside the [], so `tensor[ [] ]`

> Always returns a copy

In [ ]:
idx = [2,3,4]

tensor2 = torch.arange(11)
print(tensor2[idx])

"""
1D TECHNIQUE: Get the idx 
"""

tensor([2, 3, 4])


In [34]:
tensor2 = torch.randn(4,4)
print(f'Complete matrix:\n{tensor2}')
print(f'Selected rows of the matrix (2 and 3):\n{tensor2[[1,2]]}')

"""
2D TECHNIQUE 1: Get the row complete
"""

Complete matrix:
tensor([[-0.8117,  1.1128, -1.3075, -0.4324],
        [-0.5031,  1.3566, -0.3610,  0.3964],
        [ 0.7967,  0.2860,  1.5531, -0.6506],
        [ 0.0911, -0.0834, -2.0347,  1.0481]])
Selected rows of the matrix (2 and 3):
tensor([[-0.5031,  1.3566, -0.3610,  0.3964],
        [ 0.7967,  0.2860,  1.5531, -0.6506]])


'\n2D TECHNIQUE 1: Get the row complete\n'

In [36]:
print(f'Complete matrix:\n{tensor2}')
print(f'Selected points of the matrix (1,1) and (2,2):\n{tensor2[[1, 2], [1, 2]]}')

"""
2D TECHNIQUE 1: Get the specific points (x, y)
# Logic [row], [col] -> so [1, 2], [2, 2]

Means get the row idx (1) with the col idx 2 (1, 2)
"""

Complete matrix:
tensor([[-0.8117,  1.1128, -1.3075, -0.4324],
        [-0.5031,  1.3566, -0.3610,  0.3964],
        [ 0.7967,  0.2860,  1.5531, -0.6506],
        [ 0.0911, -0.0834, -2.0347,  1.0481]])
Selected points of the matrix (1,1) and (2,2):
tensor([1.3566, 1.5531])


'\n2D TECHNIQUE 1: Get the specific points (x, y)\n# Logic [row], [col] -> so [1, 2], [2, 2]\n\nMeans get the row idx (1) with the col idx 2 (1, 2)\n'

### 3. Boolean Indexation

Select elements using conditions

> Always returns a copy

In [23]:
tensor3 = torch.arange(10)
print(f'Selecting elemnts bigger than 5: {tensor[tensor > 5]}')

Selecting elemnts bigger than 5: tensor([ 6,  7,  8,  9, 10])


### 4. Gather

"Give me the value of this idx"

In [68]:
tensor4 = torch.rand(4, 4)
idx = torch.tensor([0, 1, 2, 3])

print(f'Matrix complete:{tensor4}')
print(tensor4.gather(1, idx.unsqueeze(1)))


Matrix complete:tensor([[0.6669, 0.2199, 0.5374, 0.1413],
        [0.3344, 0.0483, 0.2894, 0.9744],
        [0.7181, 0.0214, 0.1897, 0.3996],
        [0.9772, 0.4103, 0.7808, 0.6275]])
tensor([[0.6669],
        [0.0483],
        [0.1897],
        [0.6275]])


### 5. Scatter

Some logic of gather but instead of read, gonna write a value

In [67]:
tensor4 = torch.rand(4, 4)
idx = torch.tensor([0, 1, 2, 3])


print(f'Matrix before:\n{tensor4}')

print()
print(f'Tensor after the scatter:\n{tensor4.scatter(1, idx.unsqueeze(1), 10)}')

Matrix before:
tensor([[0.3946, 0.4804, 0.2337, 0.4277],
        [0.6018, 0.4242, 0.8515, 0.2681],
        [0.1681, 0.8688, 0.9794, 0.0537],
        [0.4019, 0.2394, 0.8683, 0.0275]])

Tensor after the scatter:
tensor([[10.0000,  0.4804,  0.2337,  0.4277],
        [ 0.6018, 10.0000,  0.8515,  0.2681],
        [ 0.1681,  0.8688, 10.0000,  0.0537],
        [ 0.4019,  0.2394,  0.8683, 10.0000]])
