In [20]:
import numpy as np
import torch

## 1. Tensors and `dtype`

You you should know that numpy matrix and tensors have their <class.numpy dtype>, in PyTorch, the object gonna be in a <class.torch dtype> the main different between them it's the device (where your data are allocate) PyTorch allows that you use your GPU and CPU, wheres Numpy it's only CPU

If you are using both and doesn't know in which you matrix are, you can use the `.dtype` to see

In [21]:



np_array = np.array([1,2,3])
torch_array = torch.tensor([1,2,3])

print(f'Numpy Array: {np_array.dtype}')
print(f'Torch Array: {torch_array.dtype}')

Numpy Array: int64
Torch Array: torch.int64


### 1.1 How to changes each other

`torch.from_numpy()` does not allocate new memory, it creates a tensor
that points to the same memory block as the original NumPy array.
Any mutation on either object will reflect on the other, since they
share the same underlying data.

> Instead the torch.tensor() will create another variable, so they'll become independent from each other, while .from_numpy will be the same

In [22]:
np_array = np.array([1,2,3])
torch_array = torch.from_numpy(np_array)

print(f'Numpy Array: {np_array.dtype}')
print(f'Torch Array: {torch_array.dtype}')

Numpy Array: int64
Torch Array: torch.int64


## 2. Tensors Creates


### Fixed Value

- `torch.zeros(x, y)` Create a matrix or tensors (x,y) with 0
- `torch.ones(x, y)` Create a matrix or tensors (x,y) with 1
- `torch.full((x, y), v)` Create a matrix or tensor (x, y) with a fixed value of v
- `torch.tensor(x)` Create a matrix or tensor (in the way that just put in a torch way)

### Sequencsy and Ranges

- `torch.arange(x, y, a)` Create a matrix or tensor in a sequency in a in a
- `torch.linspace(x, y, step=v)` Create a matrix or tensor in a squency in v steps

### Randoms

- `torch.rand(x, y)` Create a random matrix (x, y) with numbers between 0 and 1
- `torch.randn(x, y)` Create a random matrix (x, y) with numbers with medium 1 and dp = 1
- `torch.randint(a, b, (x, y))` Create a random matrix (x, y) with numbers between a and b



In [23]:
zeros_m = torch.zeros(2,2)
ones_m = torch.ones(2, 2)
fulls_m = torch.full((2, 2), 4)

print(f'Matrix of zeros:\n{zeros_m}\n')
print(f'Matrix of ones:\n{ones_m}\n')
print(f'Matrix of fulls:\n{fulls_m}\n')

arange = torch.arange(0, 10, 2)
linspace = torch.linspace(0, 10, 5)

print(f'Matrix of arange: {arange}')
print(f'Matrix of linspace: {linspace}\n')


random = torch.rand(2, 2)
randomn = torch.rand(2, 2)
randint = torch.randint(0, 10, (2, 2))

print(f'Matrix of random: \n{random}\n')
print(f'Matrix of randomn: \n{randomn}\n')
print(f'Print of random int nunbers: \n{randint}\n')

Matrix of zeros:
tensor([[0., 0.],
        [0., 0.]])

Matrix of ones:
tensor([[1., 1.],
        [1., 1.]])

Matrix of fulls:
tensor([[4, 4],
        [4, 4]])

Matrix of arange: tensor([0, 2, 4, 6, 8])
Matrix of linspace: tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

Matrix of random: 
tensor([[0.2797, 0.3910],
        [0.2239, 0.6018]])

Matrix of randomn: 
tensor([[0.4612, 0.9709],
        [0.1097, 0.9449]])

Print of random int nunbers: 
tensor([[3, 1],
        [0, 0]])



### 2.1 `torch.tensor` vs `torch.Tensor`

1. `torch.tensor` Create a tensor and you can change the dtype
2. `torch.Tensor` Create a tensor and you can't change the dtype, it always float32

In [25]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.Tensor([1,2,3])

print(f'Tensor1:\n{tensor1}, dtype: {tensor1.dtype}\n')
print(f'Tensor2:\n{tensor2}, dtype: {tensor2.dtype}')


Tensor1:
tensor([1, 2, 3]), dtype: torch.int64

Tensor2:
tensor([1., 2., 3.]), dtype: torch.float32
