In [15]:
import torch

# 1. Mul (Element-wise Multiplication or *)

Multiplies corresponding elements. Output shape equals input shape

For this operations occurs both vector, matrixs or tensors needs to have the exactly same shape

- We can use two options:
1. PyTorch: `torch.mul(x, y)`
2. Python : `x * y`

In [16]:
matrix1 = torch.rand(2, 2)
matrix2 = torch.rand(2, 2)

# Way1
mul1 = torch.mul(matrix1, matrix2)
# Way 2
mul2 = matrix1 * matrix2

print(f'Matrix 1 Elements:\n{matrix1}')
print(f'Matrix 2 Elements:\n{matrix2}')

print(f'Mult 1:\n{mul1}')
print(f'Mult 2:\n{mul2}')

"""

0.1992 * 0.2706, 0.1971 * 0.1751
0.3914 * 1030, 0.1575 * 0.1166


"""

Matrix 1 Elements:
tensor([[0.4848, 0.5306],
        [0.0988, 0.0440]])
Matrix 2 Elements:
tensor([[0.2526, 0.3119],
        [0.9828, 0.9713]])
Mult 1:
tensor([[0.1225, 0.1655],
        [0.0971, 0.0427]])
Mult 2:
tensor([[0.1225, 0.1655],
        [0.0971, 0.0427]])


'\n\n0.1992 * 0.2706, 0.1971 * 0.1751\n0.3914 * 1030, 0.1575 * 0.1166\n\n\n'

# 2. Dot Product 

A dot product multiplies corresponding elements of two vectors and sums the results into a single scalar. It is the fundamental operation that measures **how much two vectors align**

For this operations the shapes need to be x = (m, n) // y = (n, p), and the output shape gonna be (m, p)


- We same some options:
1. (1D): `torch.dot(x, y)`
2. (2D+): `torch.matmul(x, y)`
3. (2D+): `x @ y`

In [17]:

matrix1 = torch.rand(5)
matrix2 = torch.rand(5)
matrix3 = torch.rand(2, 3)
matrix4 = torch.rand(3, 2)

# Way1
mul1 = torch.dot(matrix1, matrix2)

# Way 2
mul2 = torch.matmul(matrix3, matrix4)

# Way 3
mul3 = matrix3 @ matrix4

print(f'Matrix 1 Elements:{matrix1}')
print(f'Matrix 2 Elements:{matrix2}')

print(f'Mult 1 = {mul1:.3f}\n')
print(f'=' * 50)

print(f'Matrix 3 Elements:\n{matrix3}\n')
print(f'Matrix 4 Elements:\n{matrix4}\n')
print(f'Mult 2:\n{mul2}\n')
print(f'Mult 3:\n{mul3}\n')


Matrix 1 Elements:tensor([0.9111, 0.8006, 0.4028, 0.7225, 0.0024])
Matrix 2 Elements:tensor([0.6793, 0.7289, 0.2366, 0.1761, 0.7162])
Mult 1 = 1.427

Matrix 3 Elements:
tensor([[0.7828, 0.0761, 0.9661],
        [0.8492, 0.6185, 0.4953]])

Matrix 4 Elements:
tensor([[0.4666, 0.4041],
        [0.1675, 0.4622],
        [0.1617, 0.5794]])

Mult 2:
tensor([[0.5342, 0.9113],
        [0.5799, 0.9160]])

Mult 3:
tensor([[0.5342, 0.9113],
        [0.5799, 0.9160]])



# 3. Unary


1. Abs: Removes the sign — negative values turn positive, positive become equal.
2. Neg: Inverts the sign of each element.
3. Sqrt: Square root. It only works at negative values ≥ 0 — return nan.
4. Exp: Raises e ≈ 2,718 to the power of each element.
5. Log: Natural logarithm. Inverse of exp. Only for values > 0 — zero and negative return -inf or nan.
6. Clamp: Limits values between a minimum and a maximum. Values outside the range are cut
7. Sign: Returns only the sign: -1, 0, or +1.



In [18]:
one = torch.tensor([-3])
two = torch.tensor([144])
tree = torch.tensor([2])

abs = torch.abs(one)
neg = torch.neg(one)
sqrt = torch.sqrt(two)
exp = torch.exp(tree)
log = torch.log10(tree) # basis 10
clamp = torch.clamp(two, max=10, min=1)
sign = torch.sign(tree)

print(f'ABS of {one[0]} = {abs}')
print(f'NEG of {one[0]} = {neg}')
print(f'SQRT of {two[0]} = {sqrt}')
print(f'EXP of {tree[0]} = {exp}')
print(f'LOG of {tree[0]} = {log}')
print(f'CLAMP of {two[0]} (min 1, max 10) = {clamp}')
print(f'SIGN of {tree[0]} = {sign}')

ABS of -3 = tensor([3])
NEG of -3 = tensor([3])
SQRT of 144 = tensor([12.])
EXP of 2 = tensor([7.3891])
LOG of 2 = tensor([0.3010])
CLAMP of 144 (min 1, max 10) = tensor([10])
SIGN of 2 = tensor([1])


# 4. Broadcasting — NumPy / PyTorch

Lets you operate on arrays/tensors of **different shapes** without manually resizing them. The smaller array is automatically "stretched" to match the bigger one.

## Scalar + Array

```python
arr = np.array([1, 2, 3])
arr + 10
# -> [11, 12, 13]
```

`10` is stretched to `[10, 10, 10]` automatically.

## Matrix + Vector

```python
mat = np.array([[1,2,3],
                  [4,5,6]])
vec = np.array([10,20,30])

mat + vec
# -> [[11,22,33],
#     [14,25,36]]
```

`vec` (shape `(3,)`) is applied to **every row** of `mat` (shape `(2,3)`).

## Broadcasting Rule

Two dimensions are compatible if:
- they are equal, OR
- one of them is 1 (gets stretched)

```python
mat.shape   # (2, 3)
vec.shape   # (3,)  -> treated as (1,3), stretched to (2,3)
```

## Common ML Use

```python
X = np.random.rand(100, 5)   # 100 samples, 5 features
mean = X.mean(axis=0)          # shape (5,)
X_norm = X - mean                 # broadcasting applies subtraction per row
```

Used constantly for: normalization, adding bias per neuron, combining embeddings — no loops needed.

# 5. Reductions — NumPy / PyTorch

Operations that collapse an array/tensor into fewer values (sum, mean, max, etc).

## No axis — reduces everything to one value

```python
mat = np.array([[1,2,3],
                  [4,5,6]])

mat.sum()    # 21
mat.mean()   # 3.5
mat.max()    # 6
```

## With `axis` (NumPy) / `dim` (PyTorch) — reduces only one dimension

```python
mat.sum(axis=0)   # sum per COLUMN -> [5, 7, 9]
mat.sum(axis=1)   # sum per ROW    -> [6, 15]
```

**How to think about `axis`:** it's the axis that **disappears** after the operation.

- `axis=0` → collapses rows → 1 value per **column**
- `axis=1` → collapses columns → 1 value per **row**

```python
mat.shape                # (2, 3)
mat.sum(axis=0).shape    # (3,)  -> rows gone
mat.sum(axis=1).shape    # (2,)  -> columns gone
```

## Common reductions

```python
arr.sum(axis=0)      # sum
arr.mean(axis=0)     # mean
arr.max(axis=0)      # max value
arr.min(axis=0)      # min value
arr.std(axis=0)      # standard deviation
arr.var(axis=0)      # variance
arr.argmax(axis=0)   # INDEX of the max (not the value)
arr.argmin(axis=0)   # index of the min
arr.prod(axis=0)     # product of all values
arr.any(axis=0)      # is any True?
arr.all(axis=0)      # are all True?
```

## Common ML use

```python
X.mean(axis=0)   # per-feature mean (used for normalization)
X.std(axis=0)    # per-feature std

# classic example: get predicted class
probs = torch.tensor([[0.1, 0.7, 0.2],
                        [0.6, 0.3, 0.1]])
probs.argmax(dim=1)   # -> [1, 0] (index of highest prob per row)
```

In [19]:
import torch

matrix = torch.rand(4, 4)
print(matrix)

tensor([[0.5627, 0.2763, 0.3384, 0.8615],
        [0.5852, 0.4465, 0.2368, 0.0097],
        [0.0926, 0.4952, 0.1203, 0.2738],
        [0.8975, 0.1081, 0.2577, 0.3893]])


In [20]:
mean = matrix.mean()
sum = matrix.sum()
max = matrix.max()

print(mean, sum, max)

tensor(0.3720) tensor(5.9516) tensor(0.8975)


In [21]:
mean = matrix.mean(dim=0)
sum = matrix.sum(dim=0)
max = matrix.max(dim=0)

print(f'Sum of values: {sum}')
print(f'Mean of the values: {mean}')
print(f'Max values: {max}')


Sum of values: tensor([2.1380, 1.3261, 0.9532, 1.5343])
Mean of the values: tensor([0.5345, 0.3315, 0.2383, 0.3836])
Max values: torch.return_types.max(
values=tensor([0.8975, 0.4952, 0.3384, 0.8615]),
indices=tensor([3, 2, 0, 0]))


 > dim 0 = vertical //
 > dim 1 = horizontal