In [1]:
import torch

# 1. Mul (Element-wise Multiplication or *)

Multiplies corresponding elements. Output shape equals input shape

For this operations occurs both vector, matrixs or tensors needs to have the exactly same shape

- We can use two options:
1. PyTorch: `torch.mul(x, y)`
2. Python : `x * y`

In [ ]:
matrix1 = torch.rand(2, 2)
matrix2 = torch.rand(2, 2)

# Way1
mul1 = torch.mul(matrix1, matrix2)
# Way 2
mul2 = matrix1 * matrix2

print(f'Matrix 1 Elements:\n{matrix1}')
print(f'Matrix 2 Elements:\n{matrix2}')

print(f'Mult 1:\n{mul1}')
print(f'Mult 2:\n{mul2}')

"""

0.1992 * 0.2706, 0.1971 * 0.1751
0.3914 * 1030, 0.1575 * 0.1166


"""

Matrix 1 Elements:
tensor([[0.1992, 0.1971],
        [0.3914, 0.1575]])
Matrix 2 Elements:
tensor([[0.2706, 0.1751],
        [0.1030, 0.1166]])
Mult 1:
tensor([[0.0539, 0.0345],
        [0.0403, 0.0184]])
Mult 2:
tensor([[0.0539, 0.0345],
        [0.0403, 0.0184]])


# 2. Dot Product 

A dot product multiplies corresponding elements of two vectors and sums the results into a single scalar. It is the fundamental operation that measures **how much two vectors align**

For this operations the shapes need to be x = (m, n) // y = (n, p), and the output shape gonna be (m, p)


- We same some options:
1. (1D): `torch.dot(x, y)`
2. (2D+): `torch.matmul(x, y)`
3. (2D+): `x @ y`

In [18]:

matrix1 = torch.rand(5)
matrix2 = torch.rand(5)
matrix3 = torch.rand(2, 3)
matrix4 = torch.rand(3, 2)

# Way1
mul1 = torch.dot(matrix1, matrix2)

# Way 2
mul2 = torch.matmul(matrix3, matrix4)

# Way 3
mul3 = matrix3 @ matrix4

print(f'Matrix 1 Elements:{matrix1}')
print(f'Matrix 2 Elements:{matrix2}')

print(f'Mult 1 = {mul1:.3f}\n')
print(f'=' * 50)

print(f'Matrix 3 Elements:\n{matrix3}\n')
print(f'Matrix 4 Elements:\n{matrix4}\n')
print(f'Mult 2:\n{mul2}\n')
print(f'Mult 3:\n{mul3}\n')


Matrix 1 Elements:tensor([0.5234, 0.4851, 0.6759, 0.4598, 0.8238])
Matrix 2 Elements:tensor([0.1068, 0.4986, 0.5892, 0.8280, 0.2995])
Mult 1 = 1.323

Matrix 3 Elements:
tensor([[0.1095, 0.7806, 0.3580],
        [0.7213, 0.3119, 0.9925]])

Matrix 4 Elements:
tensor([[0.4592, 0.2294],
        [0.6695, 0.9190],
        [0.0831, 0.7254]])

Mult 2:
tensor([[0.6026, 1.0022],
        [0.6224, 1.1721]])

Mult 3:
tensor([[0.6026, 1.0022],
        [0.6224, 1.1721]])



# 3. Unary


1. Abs: Removes the sign — negative values turn positive, positive become equal.
2. Neg: Inverts the sign of each element.
3. Sqrt: Square root. It only works at negative values ≥ 0 — return nan.
4. Exp: Raises e ≈ 2,718 to the power of each element.
5. Log: Natural logarithm. Inverse of exp. Only for values > 0 — zero and negative return -inf or nan.
6. Clamp: Limits values between a minimum and a maximum. Values outside the range are cut
7. Sign: Returns only the sign: -1, 0, or +1.



In [29]:
one = torch.tensor([-3])
two = torch.tensor([144])
tree = torch.tensor([2])

abs = torch.abs(one)
neg = torch.neg(one)
sqrt = torch.sqrt(two)
exp = torch.exp(tree)
log = torch.log10(tree) # basis 10
clamp = torch.clamp(two, max=10, min=1)
sign = torch.sign(tree)

print(f'ABS of {one[0]} = {abs}')
print(f'NEG of {one[0]} = {neg}')
print(f'SQRT of {two[0]} = {sqrt}')
print(f'EXP of {tree[0]} = {exp}')
print(f'LOG of {tree[0]} = {log}')
print(f'CLAMP of {two[0]} (min 1, max 10) = {clamp}')
print(f'SIGN of {tree[0]} = {sign}')

ABS of -3 = tensor([3])
NEG of -3 = tensor([3])
SQRT of 144 = tensor([12.])
EXP of 2 = tensor([7.3891])
LOG of 2 = tensor([0.3010])
CLAMP of 144 (min 1, max 10) = tensor([10])
SIGN of 2 = tensor([1])
